version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend/src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - default
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - 9906:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
  client:
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4000:80
    networks:
      - default

networks:
  default: